add JMX port to QA resource report

diff --git a/driver-extensions/shell-scripts/bin/com-qa-report b/driver-extensions/shell-scripts/bin/com-qa-report
--- a/driver-extensions/shell-scripts/bin/com-qa-report
+++ b/driver-extensions/shell-scripts/bin/com-qa-report
@@ -1,7 +1,13 @@
 #!/bin/sh
+#
+# com-qa-report captures log files and various information from nodetool from all available nodes.
+# Information from scheduler is currently not included.
+# Archived Cassandra log files are also not included.
+#
 
-_BINARY=bin/cqlsh
-. `dirname $0`/com.api.in.sh
+_BINARY=bin/nodetool
+_LIVE_NODES_TYPE=nodetool
+. `dirname $0`/com.in.sh
 
 targetDir="qa-report-`date '+%Y-%m-%d-%H-%M-%S'`"
 if [ ! -z $1 ] ; then
@@ -10,12 +16,30 @@ fi
 
 echo "Downloading QA report files to ${targetDir}"
 
+function nodetoolInvoke() {
+    ${EXEC} -h $1 -p $2 $3 > $4/nodetool-$3.txt 2>&1
+    ec=$?
+    if [ "0" != "${ec}" ] ; then
+        echo "** nodetool $3 against ${currentIp} failed with exit code ${ec}"
+    fi
+}
+
 curl -s "${API_BASE_URI}qaReportResources/text" | while read ln ; do
     case $ln in
+        JMX:*)
+            jmxPort="`echo $ln | cut -d\  -f 2`"
+            ;;
         IP:*)
             currentIp="`echo $ln | cut -d\  -f 2`"
-            echo "Retrieving log files from ${currentIp}"
             mkdir -p ${targetDir}/${currentIp}
+
+            echo "Retrieving nodetool information from ${currentIp}"
+            nodetoolInvoke ${currentIp} ${jmxPort} version "${targetDir}/${currentIp}"
+            nodetoolInvoke ${currentIp} ${jmxPort} info "${targetDir}/${currentIp}"
+            nodetoolInvoke ${currentIp} ${jmxPort} status "${targetDir}/${currentIp}"
+            nodetoolInvoke ${currentIp} ${jmxPort} tpstats "${targetDir}/${currentIp}"
+
+            echo "Retrieving log files from ${currentIp}"
             ;;
         BASE:*)
             currentBaseUri="`echo $ln | cut -d\  -f 2`"
